baseurl: https://benderblog.github.io
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: SuperBart/BenderBlog

# Change it to your Disqus shortname before using
#disqusShortname: hugo-theme-stack

# GA Tracking ID
#googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

relativeURLs: true
uglyURLs: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: img/avatar.png

    footer:
        since: 2021
        customText: <strong><a href="https://icp.gov.moe/?keyword=20220626" target="_blank">萌ICP备20220626号</a></strong>

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle: 欢迎来到SuperBart/BenderBlog的自留地
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: 如果没有注明，所有文字资料，按照CC BY-SA 4.0授权，图片资料按照CC BY 4.0授权

    comments:
        enabled: false

    widgets:
        enabled:
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    #opengraph:
    #    twitter:
            # Your Twitter username
    #        site:

            # Available values: summary, summary_large_image
     #       card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: 主页
          url: /
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: home
        - identifier: older
          name: 老版博客
          url: https://legacy.superbart.xyz
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: link
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/BenderBlog
          params:
            icon: brand-github

        - identifier: bilibili
          name: Bilibili
          url: https://space.bilibili.com/284290692
          params:
            icon: brand-bilibili

        - identifier: email
          name: EMail
          url: mailto:superbart_chen@qq.com
          params:
            icon: mail

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
